# JDK 베이스 이미지 선택 (17 이상 권장)
FROM eclipse-temurin:17-jdk-alpine

# 작업 디렉토리
WORKDIR /api-server

COPY build/libs/stroll-api-0.0.1-SNAPSHOT.jar stroll-api.jar

# 컨테이너에서 열 포트 (Spring Boot 기본 8080)
EXPOSE 8080

ENTRYPOINT ["java","-jar","stroll-api.jar"]